name: Release Kernel

on:
  workflow_dispatch:

jobs:
  download-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release info
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
               https://api.github.com/repos/qlenlen/kernel_samsung_sm8550/releases/latest \
               -o release_info.json
          cat release_info.json
          mkdir assets

      - name: Download all assets
        run: |
          ASSET_INFO=$(jq -r '.assets[] | "\(.id) \(.name)"' release_info.json)
          while IFS= read -r line; do
            ASSET_ID=$(echo $line | awk '{print $1}')
            echo $ASSET_ID
            ASSET_NAME=$(echo $line | awk '{print $2}')
            echo $ASSET_NAME

            curl -L -H "Authorization: token ${{ secrets.TOKEN }}" \
              -H "Accept: application/octet-stream" \
              "https://api.github.com/repos/qlenlen/kernel_samsung_sm8550/releases/assets/$ASSET_ID" \
              -o $ASSET_NAME
          done <<<"$ASSET_INFO"
          mv *.zip assets

      - name: Upload assets
        uses: actions/upload-artifact@v4.3.5
        with:
          name: kernel_samsung_dm3q
          path: assets

      - name: Generate TAG
        run: |
          DATE=$(date +'%y.%m.%d')
          echo "TAG=$DATE" >> $GITHUB_ENV

      - name: Upload release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "assets/*.zip"
          allowUpdates: true
          name: "kernel_samsung_dm3q"
          tag: "CI_${{ env.TAG }}"
          body: |
            ### Note: 
            Flash the kernel zip with [kernel flasher](https://github.com/qlenlen/KernelFlasher/releases) or TWRP
            When using KSU-GKI mode, there is no need to patch anything
            But if you prefer LKM more, do not forget to patch your init_boot

            ### CHANGELOG

            ### 更新日志
